### ISSUE TITLE
checkpoint resume & model save

### ISSUE THREAD

**Issue by hotarujun** [bwconrad/vit-finetune#10]
Hello, again!
  
  My training was interrupted on the 7th epoch, but luckily there was 2 ckpt files left. I wonder how to resume training with these files? I searched for the code with the keyword "save" and found the following information:
  ```
class MyLightningCLI(LightningCLI):
    def add_arguments_to_parser(self, parser) -> None:
        parser.add_lightning_class_args(ModelCheckpoint, "model_checkpoint")
        parser.set_defaults(
            {
                "trainer.logger": lazy_instance(
                    CSVLogger, save_dir="output", name="default"
                ),
                "model_checkpoint.monitor": "val_acc",
                "model_checkpoint.mode": "max",
                "model_checkpoint.filename": "best-step-{step}-{val_acc:.4f}",
                "model_checkpoint.save_last": True,
            }
        )
        parser.link_arguments("data.size", "model.image_size")
        parser.link_arguments(
            "data.num_classes", "model.n_classes", apply_on="instantiate"
        )
```
  But I didn't find code to save the model like `torch.save(model,model_path)` . Or it's unnecessary ? What should I do if I need to save the model?

  Thank you so much for reading this far, and have a great day！

**Comment by bwconrad** [comment]
You can resume from a checkpoint file with `--ckpt_path` argument. 

None of the checkpoint saving and loading is explicitly written in this repo since its all done by PyTorch Lightning. You can see the list of training arguments with `python main.py fit --help` and more details about the arguments can be found in the [lighning docs](https://lightning.ai/docs/pytorch/stable/).
