### ISSUE TITLE
custom dataset training error

### ISSUE THREAD

**Issue by krishnaadithya** [bwconrad/vit-finetune#3]
ValueError: custom  is not an available dataset. Should be one of ['cifar10', 'cifar100', 'flowers102', 'food101', 'pets37', 
'stl10', 'dtd', 'aircraft', 'cars']

python main.py fit --trainer.accelerator gpu --trainer.devices 1 --trainer.precision 16-mixed --trainer.max_steps 5000 --model.warmup_steps 500 --model.lr 0.01 --trainer.val_check_interval 500 --data.batch_size 128 --data.dataset custom  --data.num_classes 2 --data.root path

**Comment by bwconrad** [comment]
I cannot replicate this error when using the command you provided. I did make a commit fixing a different error that your command raises related to the top5 acc when using <5 classes. 

Are you using the most recent commit and are you sure that "custom" is being spelled correctly?

**Comment by krishnaadithya** [comment]
thie is exactly what I tried running: python main.py fit --trainer.accelerator gpu --trainer.devices 1 --trainer.precision 16-mixed --trainer.max_steps 5000 --model.warmup_steps 500 --model.lr 0.01 --trainer.val_check_interval 500 --data.batch_size 128 --data.dataset custom  --data.num_classes 2 --data.root ’../dataset/disc_no_disc/‘ 

this is the error I get:
ValueError: custom  is not an available dataset. Should be one of ['cifar10', 'cifar100', 'flowers102', 'food101', 'pets37', 'stl10', 'dtd', 'aircraft', 'cars']

**Comment by bwconrad** [comment]
Again I can not replicate the error you are getting and without being able to replicate it I can't do much to debug this. This is the if statement that is failing: 

https://github.com/bwconrad/vit-finetune/blob/8d218fc649e330e026ef189cd5d751cafa1a47e1/src/data.py#L136-L164

The only thing I can think of this that you are using a non English keyboard input method and that you are accidentally  inputting homoglyphs instead of the regular characters (see [here](https://gist.github.com/StevenACoffman/a5f6f682d94e38ed804182dc2693ed4b)) which causes the comparison to fail.
