### ISSUE TITLE
Results available for other datasets ?

### ISSUE THREAD

**Issue by AlbinSou** [bwconrad/vit-finetune#7]
Hello,

Thank you for the code and the helpful tricks.

Do you have the results for the other available datasets ? I'm trying to finetune a LoRA on Stanford Cars and it would be very helpful to have the results for comparison.

**Comment by bwconrad** [comment]
Sorry, what's in the readme are all the results that I personally have. So I do not have any numbers for Standard Cars. 

Since there really aren't many results out there for lora finetuning on vision datasets, I generally just aim to get close to full finetuning results, since all the datasets I've tried out could achieve this. [This paper](https://arxiv.org/abs/2203.07845) got 93.3 with linear probe on a ViT-B so I would compare with that and the full finetune results [here](https://paperswithcode.com/sota/fine-grained-image-classification-on-stanford).
